In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.metrics import precision_score
from sklearn.metrics import confusion_matrix,accuracy_score,roc_curve,classification_report
from sklearn.linear_model import LogisticRegression
from sklearn.utils.validation import column_or_1d
from sklearn.svm import SVC
from sklearn.neural_network import MLPClassifier
from sklearn.neural_network import MLPRegressor
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import KFold

In [2]:
df = pd.read_csv('du_lieu_chuan.csv')
df

Unnamed: 0  gender  SeniorCitizen  Partner  Dependents  tenure  \
0              0       0              0        1           0       1   
1              1       1              0        0           0      34   
2              2       1              0        0           0       2   
3              3       1              0        0           0      45   
4              4       0              0        0           0       2   
5              5       0              0        0           0       8   
6              6       1              0        0           1      22   
7              7       0              0        0           0      10   
8              8       0              0        1           0      28   
9              9       1              0        0           1      62   
10            10       1              0        1           1      13   
11            11       1              0        0           0      16   
12            12       1              0        1           0      58   
13            13       1              0        0           0      49   
14            14       1              0        0           0      25   
15            15       0              0        1           1      69   
16            16       0              0        0           0      52   
17            17       1              0        0           1      71   
18            18       0              0        1           1      10   
19            19       0              0        0           0      21   
20            20       1              1        0           0       1   
21            21       1              0        1           0      12   
22            22       1              0        0           0       1   
23            23       0              0        1           0      58   
24            24       1              0        1           1      49   
25            25       0              0        0           0      30   
26            26       1              0        1           1      47   
27            27       1              0        1           1       1   
28            28       1              0        1           0      72   
29            29       0              0        0           1      17   
...          ...     ...            ...      ...         ...     ...   
7002        7013       0              0        0           0      40   
7003        7014       1              0        0           0      41   
7004        7015       1              1        1           0      34   
7005        7016       0              0        0           0       1   
7006        7017       0              0        0           0      51   
7007        7018       1              0        1           1       1   
7008        7019       0              0        0           0      39   
7009        7020       1              0        1           1      12   
7010        7021       1              0        0           0      12   
7011        7022       1              0        0           0      72   
7012        7023       0              1        1           0      63   
7013        7024       1              0        1           0      44   
7014        7025       0              0        0           0      18   
7015        7026       0              0        0           0       9   
7016        7027       1              0        0           0      13   
7017        7028       0              0        1           0      68   
7018        7029       0              1        0           0       6   
7019        7030       0              0        0           0       2   
7020        7031       1              1        1           0      55   
7021        7032       1              1        0           0       1   
7022        7033       1              0        0           0      38   
7023        7034       0              0        0           0      67   
7024        7035       1              0        0           0      19   
7025        7036       0              0       

In [3]:
df.head()

Unnamed: 0  gender  SeniorCitizen  Partner  Dependents  tenure  \
0           0       0              0        1           0       1   
1           1       1              0        0           0      34   
2           2       1              0        0           0       2   
3           3       1              0        0           0      45   
4           4       0              0        0           0       2   

   PhoneService  MultipleLines  InternetService  OnlineSecurity  ...  \
0             0              2                1               0  ...   
1             1              0                1               1  ...   
2             1              0                1               1  ...   
3             0              2                1               1  ...   
4             1              0                2               0  ...   

   DeviceProtection  TechSupport  StreamingTV  StreamingMovies  Contract  \
0                 0            0            0                0         0   
1                 1            0            0                0         1   
2                 0            0            0                0         0   
3                 1            1            0                0         1   
4                 0            0            0                0         0   

   PaperlessBilling  PaymentMethod  MonthlyCharges  TotalCharges  Churn  
0                 1              0           29.85         29.85      0  
1                 0              1           56.95       1889.50      0  
2                 1              1           53.85        108.15      1  
3                 0              2           42.30       1840.75      0  
4                 1              0           70.70        151.65      1  

[5 rows x 21 columns]

In [4]:
df.shape

(7032, 21)

In [5]:
df.drop('Unnamed: 0', axis=1, inplace=True)

In [6]:
X = df.loc[:, df.columns != 'Churn']
y = df.loc[:, df.columns == 'Churn']

In [7]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30, random_state = 0)

In [8]:
SScalers = StandardScaler()
X_train = SScalers.fit_transform(X_train)
X_test = SScalers.transform(X_test)

In [9]:
model1 = 'Logistic Regression'

In [10]:
clf_lr = LogisticRegression()

In [11]:
clf_lr.fit(X_train, column_or_1d(y_train))

C:\Users\hp\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [12]:
clf_lr.intercept_

array([-1.72213126])

In [13]:
clf_lr.coef_

array([[ 0.0108891 ,  0.12387518,  0.04098399, -0.10758548, -1.40364722,
         0.08686172,  0.21840238,  0.78466013, -0.22297809, -0.14899208,
         0.10336726, -0.2672644 ,  0.23584595,  0.27057902, -0.56329216,
         0.2317912 , -0.20389243, -0.33979422,  0.6322174 ]])

In [14]:
Yhat_train =clf_lr.predict(X_train)

In [15]:
Yhat_test = clf_lr.predict(X_test)

In [16]:
clf_lr_conf_matrix = confusion_matrix(y_test, Yhat_test)

In [17]:
clf_lr_acc_score = accuracy_score(y_test, Yhat_test)

In [18]:
print("confussion matrix")
print(clf_lr_conf_matrix)
print("\n")
print("Accuracy of Logistic Regression:",clf_lr_acc_score*100,'\n')
print(classification_report(y_test,Yhat_test))

confussion matrix
[[1389  166]
 [ 255  300]]


Accuracy of Logistic Regression: 80.04739336492891 

              precision    recall  f1-score   support

           0       0.84      0.89      0.87      1555
           1       0.64      0.54      0.59       555

    accuracy                           0.80      2110
   macro avg       0.74      0.72      0.73      2110
weighted avg       0.79      0.80      0.79      2110



In [19]:
model2 = 'Support Vector Classifier'

In [20]:
clf_svc =  SVC(kernel='rbf', C=2)

In [21]:
clf_svc.fit(X_train, y_train)

C:\Users\hp\Anaconda3\lib\site-packages\sklearn\utils\validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVC(C=2, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
    kernel='rbf', max_iter=-1, probability=False, random_state=None,
    shrinking=True, tol=0.001, verbose=False)

In [22]:
Yhat_svc_train = clf_svc.predict(X_train)

In [23]:
Yhat_svc_test = clf_svc.predict(X_test)

In [24]:
clf_svc_conf_matrix = confusion_matrix(y_test, Yhat_svc_test)
clf_svc_acc_score = accuracy_score(y_test, Yhat_svc_test)

In [25]:
print("confussion matrix")
print(clf_svc_conf_matrix)
print("\n")
print("Accuracy of Support Vector Classifier:",clf_svc_acc_score*100,'\n')
print(classification_report(y_test,Yhat_svc_test))

confussion matrix
[[1416  139]
 [ 289  266]]


Accuracy of Support Vector Classifier: 79.71563981042654 

              precision    recall  f1-score   support

           0       0.83      0.91      0.87      1555
           1       0.66      0.48      0.55       555

    accuracy                           0.80      2110
   macro avg       0.74      0.69      0.71      2110
weighted avg       0.78      0.80      0.79      2110



In [26]:
model3 = 'Neural Network'

In [27]:
clf_mlp = MLPClassifier(random_state=1, max_iter=300)

In [28]:
clf_mlp.fit(X_train, y_train)

C:\Users\hp\Anaconda3\lib\site-packages\sklearn\neural_network\multilayer_perceptron.py:921: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\hp\Anaconda3\lib\site-packages\sklearn\neural_network\multilayer_perceptron.py:566: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (300) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


MLPClassifier(activation='relu', alpha=0.0001, batch_size='auto', beta_1=0.9,
              beta_2=0.999, early_stopping=False, epsilon=1e-08,
              hidden_layer_sizes=(100,), learning_rate='constant',
              learning_rate_init=0.001, max_iter=300, momentum=0.9,
              n_iter_no_change=10, nesterovs_momentum=True, power_t=0.5,
              random_state=1, shuffle=True, solver='adam', tol=0.0001,
              validation_fraction=0.1, verbose=False, warm_start=False)

In [29]:
Yhat_mlp_train = clf_mlp.predict(X_train)

In [30]:
Yhat_mlp_test = clf_mlp.predict(X_test)

In [31]:
clf_mlp_conf_matrix = confusion_matrix(y_test, Yhat_mlp_test)
clf_mlp_acc_score = accuracy_score(y_test, Yhat_mlp_test)

In [32]:
print("confussion matrix")
print(clf_mlp_conf_matrix)
print("\n")
print("Accuracy of Neural Network:",clf_mlp_acc_score*100,'\n')
print(classification_report(y_test,Yhat_mlp_test))

confussion matrix
[[1385  170]
 [ 285  270]]


Accuracy of Neural Network: 78.43601895734598 

              precision    recall  f1-score   support

           0       0.83      0.89      0.86      1555
           1       0.61      0.49      0.54       555

    accuracy                           0.78      2110
   macro avg       0.72      0.69      0.70      2110
weighted avg       0.77      0.78      0.78      2110



In [33]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7032 entries, 0 to 7031
Data columns (total 20 columns):
gender              7032 non-null int64
SeniorCitizen       7032 non-null int64
Partner             7032 non-null int64
Dependents          7032 non-null int64
tenure              7032 non-null int64
PhoneService        7032 non-null int64
MultipleLines       7032 non-null int64
InternetService     7032 non-null int64
OnlineSecurity      7032 non-null int64
OnlineBackup        7032 non-null int64
DeviceProtection    7032 non-null int64
TechSupport         7032 non-null int64
StreamingTV         7032 non-null int64
StreamingMovies     7032 non-null int64
Contract            7032 non-null int64
PaperlessBilling    7032 non-null int64
PaymentMethod       7032 non-null int64
MonthlyCharges      7032 non-null float64
TotalCharges        7032 non-null float64
Churn               7032 non-null int64
dtypes: float64(2), int64(18)
memory usage: 1.1 MB
