In [89]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.metrics import precision_score
from sklearn.metrics import confusion_matrix,accuracy_score,roc_curve,classification_report
from sklearn.linear_model import LogisticRegression
from sklearn.utils.validation import column_or_1d
from sklearn.svm import SVC
from sklearn.neural_network import MLPClassifier
from sklearn.neural_network import MLPRegressor
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score
import seaborn as sns
import matplotlib.pyplot as plt

In [90]:
df = pd.read_csv("du_lieu_chuan.csv")

In [91]:
df.head()

Unnamed: 0  customerID  gender  SeniorCitizen  Partner  Dependents  tenure  \
0           0  7590-VHVEG       0              0        1           0       1   
1           1  5575-GNVDE       1              0        0           0      34   
2           2  3668-QPYBK       1              0        0           0       2   
3           3  7795-CFOCW       1              0        0           0      45   
4           4  9237-HQITU       0              0        0           0       2   

   PhoneService  MultipleLines  InternetService  ...  DeviceProtection  \
0             0              2                1  ...                 0   
1             1              0                1  ...                 1   
2             1              0                1  ...                 0   
3             0              2                1  ...                 1   
4             1              0                2  ...                 0   

   TechSupport  StreamingTV  StreamingMovies  Contract  PaperlessBilling  \
0            0            0                0         0                 1   
1            0            0                0         1                 0   
2            0            0                0         0                 1   
3            1            0                0         1                 0   
4            0            0                0         0                 1   

   PaymentMethod  MonthlyCharges  TotalCharges  Churn  
0              0           29.85         29.85      0  
1              1           56.95       1889.50      0  
2              1           53.85        108.15      1  
3              2           42.30       1840.75      0  
4              0           70.70        151.65      1  

[5 rows x 22 columns]

In [92]:
df.shape

(7032, 22)

In [93]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7032 entries, 0 to 7031
Data columns (total 22 columns):
Unnamed: 0          7032 non-null int64
customerID          7032 non-null object
gender              7032 non-null int64
SeniorCitizen       7032 non-null int64
Partner             7032 non-null int64
Dependents          7032 non-null int64
tenure              7032 non-null int64
PhoneService        7032 non-null int64
MultipleLines       7032 non-null int64
InternetService     7032 non-null int64
OnlineSecurity      7032 non-null int64
OnlineBackup        7032 non-null int64
DeviceProtection    7032 non-null int64
TechSupport         7032 non-null int64
StreamingTV         7032 non-null int64
StreamingMovies     7032 non-null int64
Contract            7032 non-null int64
PaperlessBilling    7032 non-null int64
PaymentMethod       7032 non-null int64
MonthlyCharges      7032 non-null float64
TotalCharges        7032 non-null float64
Churn               7032 non-null int64
dtypes: 

In [94]:
df.drop('customerID', axis=1, inplace=True)

In [95]:
df.drop('Unnamed: 0', axis=1, inplace=True)

In [96]:
cv = KFold(n_splits =10, random_state =1, shuffle = True)

KFold(n_splits=10, random_state=1, shuffle=True)

In [97]:
X = df.drop("Churn", axis=1)
y = df["Churn"]

In [98]:
cv.get_n_splits(X)
cv

KFold(n_splits=10, random_state=1, shuffle=True)

In [101]:
for train_index, test_index in cv.split(df):
    X_train, X_test = X.iloc[train_index], X.iloc[test_index]
    y_train, y_test = y[train_index], y[test_index]

In [102]:
X_train[["tenure", "TotalCharges", "MonthlyCharges"]].describe()

tenure  TotalCharges  MonthlyCharges
count  6329.000000   6329.000000     6329.000000
mean     32.422342   2287.777793       64.907955
std      24.549770   2270.599343       30.085942
min       1.000000     18.800000       18.250000
25%       9.000000    401.950000       35.750000
50%      29.000000   1391.650000       70.400000
75%      55.000000   3833.950000       90.000000
max      72.000000   8672.450000      118.750000

In [103]:
clf_lr = LogisticRegression()

In [104]:
clf_lr.fit(X_train, y_train)

C:\Users\hp\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [105]:
clf_lr.intercept_

array([-0.52164848])

In [106]:
clf_lr.coef_

array([[-3.87045577e-02,  1.48887865e-01, -4.12636974e-02,
        -1.28639989e-01, -6.08895284e-02, -1.07250167e-01,
         1.71164476e-01,  1.04481677e+00, -3.27919318e-01,
        -8.46278813e-02, -1.00951964e-02, -3.06075310e-01,
         2.99977001e-01,  3.55172791e-01, -6.82128322e-01,
         3.20198815e-01, -1.60123665e-01, -1.22734992e-02,
         3.48791993e-04]])

In [107]:
Yhat_train =clf_lr.predict(X_train)


In [108]:
Yhat_test = clf_lr.predict(X_test)

In [109]:
clf_lr_conf_matrix = confusion_matrix(y_test, Yhat_test)

In [110]:
clf_lr_acc_score = accuracy_score(y_test, Yhat_test)
clf_lr_acc_score

0.8093883357041252

In [111]:
print("confussion matrix")
print(clf_lr_conf_matrix)
print("\n")
print("Accuracy of Logistic Regression:",clf_lr_acc_score*100,'\n')
print(classification_report(y_test,Yhat_test))

confussion matrix
[[461  49]
 [ 85 108]]


Accuracy of Logistic Regression: 80.93883357041251 

              precision    recall  f1-score   support

           0       0.84      0.90      0.87       510
           1       0.69      0.56      0.62       193

    accuracy                           0.81       703
   macro avg       0.77      0.73      0.75       703
weighted avg       0.80      0.81      0.80       703



###### 

In [112]:
from sklearn.metrics import f1_score
f1_score(y_test, Yhat_test)

0.6171428571428571

In [113]:
precision_score(y_test, Yhat_test)

0.6878980891719745

In [114]:
from sklearn.metrics import recall_score
recall_score(y_test, Yhat_test)

0.5595854922279793